name: tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install poppler (for pdf2image)
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils

      - name: Set up uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          python-version: "3.13"

      # If you have a pyproject.toml with dependencies,
      # uv will resolve & install them on first `uv run`.
      # If you use a lock file, add a `uv sync` step here.

      - run: uv run pip install pytest-order

      - name: Run pytest
        run: uv run pytest -q

      # If tests fail, upload the PDFs your tests archived so you can inspect diffs
      - name: Upload generated PDFs (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: generated-pdfs
          path: |
            src/tests/generated_pdfs/**/*.pdf
            src/tests/automated_pdfs/**/*.pdf
          if-no-files-found: ignore